### ISSUE TITLE
RE: using this bundle independently ?

### ISSUE THREAD

**Issue by EugeneLiang** [tystr/TystrReactJsBundle#1]
Hi good day, 

Firstly, great work! and this package is a great addition!

May i know if this package can be used independently with other frameworks ? Such as in Slim Php or even in WordPress ?

Cheers and thanks!

**Comment by tystr** [comment]
This specifically provides functionality for the Symfony framework. It leverages the [react-php-v8js](https://github.com/reactjs/react-php-v8js) library to do hook into libv8 for the actual rendering. You could write plugins around that to achieve similar functionality in other frameworks.
